const HER_STORAGE_KEYS={BOOKS:"her_books",CURRENT_BOOK_ID:"her_current_book_id",CURRENT_CHAPTER_ID:"her_current_chapter_id",CURRENT_CHARACTER_ID:"her_current_character_id",CURRENT_BOOK_INDEX:"her_current_book_index",CURRENT_CHAPTER_INDEX:"her_current_chapter_index",USER:"her_user",SETTINGS:"her_settings",NOTES:"her_notes",THEME:"her_theme",STORY_SUGGESTIONS:"her_story_intelligence_suggestions"};
function save(k,v){localStorage.setItem(k,JSON.stringify(v));} function load(k,d=null){const x=localStorage.getItem(k);if(x===null)return d;try{return JSON.parse(x)}catch(e){console.error(e);return d}} function remove(k){localStorage.removeItem(k)} function clearStorage(){localStorage.clear()}
function getBooks(){const x=load(HER_STORAGE_KEYS.BOOKS,[]);return Array.isArray(x)?x:[]} function saveBooks(x){save(HER_STORAGE_KEYS.BOOKS,Array.isArray(x)?x:[])}
function setCurrentBookId(id){localStorage.setItem(HER_STORAGE_KEYS.CURRENT_BOOK_ID,String(id||''))} function getCurrentBookId(){return localStorage.getItem(HER_STORAGE_KEYS.CURRENT_BOOK_ID)} function getCurrentBook(){return getBooks().find(b=>b.id===getCurrentBookId())||null}
function setCurrentBookIndex(i){save(HER_STORAGE_KEYS.CURRENT_BOOK_INDEX,i);const b=getBooks()[i];if(b)setCurrentBookId(b.id)} function getCurrentBookIndex(){const a=getBooks(),id=getCurrentBookId(),i=a.findIndex(b=>b.id===id);return i>=0?i:load(HER_STORAGE_KEYS.CURRENT_BOOK_INDEX,null)}
function updateCurrentBook(u){if(!u?.id)return false;const a=getBooks(),i=a.findIndex(b=>b.id===u.id);if(i<0)return false;a[i]=u;saveBooks(a);return true}
function setCurrentChapterId(id){localStorage.setItem(HER_STORAGE_KEYS.CURRENT_CHAPTER_ID,String(id||''))} function getCurrentChapterId(){return localStorage.getItem(HER_STORAGE_KEYS.CURRENT_CHAPTER_ID)}
function setCurrentChapterIndex(i){save(HER_STORAGE_KEYS.CURRENT_CHAPTER_INDEX,i);const c=getCurrentBook()?.chapters?.[i];if(c)setCurrentChapterId(c.id)} function getCurrentChapterIndex(){const b=getCurrentBook(),id=getCurrentChapterId(),i=(b?.chapters||[]).findIndex(c=>c.id===id);return i>=0?i:load(HER_STORAGE_KEYS.CURRENT_CHAPTER_INDEX,0)}
function getUser(){return load(HER_STORAGE_KEYS.USER,null)} function saveUser(v){save(HER_STORAGE_KEYS.USER,v)} function getSettings(){return load(HER_STORAGE_KEYS.SETTINGS,{})} function saveSettings(v){save(HER_STORAGE_KEYS.SETTINGS,v)} function getNotes(){return load(HER_STORAGE_KEYS.NOTES,[])} function saveNotes(v){save(HER_STORAGE_KEYS.NOTES,v)} function getTheme(){return load(HER_STORAGE_KEYS.THEME,'dark')} function saveTheme(v){save(HER_STORAGE_KEYS.THEME,v)}
function getStorySuggestions(){return load(HER_STORAGE_KEYS.STORY_SUGGESTIONS,[])} function saveStorySuggestions(v){save(HER_STORAGE_KEYS.STORY_SUGGESTIONS,Array.isArray(v)?v:[])}
