(function(global){
'use strict';
const STOP=new Set(['The','This','That','These','Those','A','An','He','She','They','We','I','It','His','Her','Their','Our','My','Chapter','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday','January','February','March','April','May','June','July','August','September','October','November','December']);
const PLACE_WORDS='Diner|Cafe|Restaurant|Bar|Inn|Hotel|Hospital|School|University|Church|Temple|Castle|Palace|House|Home|Cabin|Farm|Ranch|Station|Airport|Park|Forest|Woods|River|Lake|Mountain|Valley|Street|Road|Avenue|Boulevard|City|Town|Village|Kingdom|Empire|Country|Island|Beach|Office|Store|Shop|Bank|Library|Prison|Jail|Court|Courthouse|Room|Kitchen|Bedroom|Hall|Garden|Garage|Warehouse|Factory|Base|Camp';
const ORG_WORDS='Company|Corporation|Department|Agency|Guild|Order|Council|Army|Church|University|Hospital|Police|FBI|CIA|Foundation|Institute|Club|Gang|Family|Syndicate|Government|Committee|Association|Team';
function sentences(text){return String(text||'').replace(/\s+/g,' ').match(/[^.!?]+[.!?]?/g)?.map(s=>s.trim()).filter(Boolean)||[]}
function norm(s){return String(s||'').trim().replace(/^["'“”‘’]+|["'“”‘’,.;:!?]+$/g,'')}
function key(s){return norm(s).toLowerCase()}
function unique(items,get=x=>x.name){const m=new Map();for(const x of items){const k=key(get(x));if(k&&!m.has(k))m.set(k,x)}return [...m.values()]}
function properNames(text){const out=[];const re=/\b([A-Z][a-zA-Z'-]{1,}(?:\s+[A-Z][a-zA-Z'-]{1,}){0,2})\b/g;for(const m of String(text||'').matchAll(re)){const n=norm(m[1]);if(!STOP.has(n)&&!new RegExp(`\\b(?:${PLACE_WORDS}|${ORG_WORDS})$`).test(n))out.push(n)}return unique(out.map(name=>({name}))).map(x=>x.name)}
function contextFor(text,name){const s=sentences(text);return s.filter(v=>new RegExp(`\\b${escapeReg(name)}\\b`,'i').test(v)).slice(0,8)}
function escapeReg(s){return String(s).replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}
function inferCharacter(name,text,chapter){const evidence=contextFor(text,name), joined=evidence.join(' ');const traits=[];const aliases=[];let occupation='';
 const occupationMatch=joined.match(new RegExp(`\\b${escapeReg(name)}\\b[^.!?]{0,70}\\b(?:was|is|worked as|served as)\\s+(?:an?\\s+|the\\s+)?([a-z][a-z -]{2,30})`,'i'))||joined.match(/\b(detective|sheriff|doctor|nurse|teacher|soldier|captain|king|queen|prince|princess|lawyer|manager|officer|agent|writer|farmer|mechanic|engineer|professor|student|waiter|waitress|bartender)\b/i);if(occupationMatch)occupation=norm(occupationMatch[1]||occupationMatch[0]);
 const traitWords=['angry','kind','quiet','nervous','brave','afraid','calm','cold','gentle','stubborn','loyal','jealous','funny','serious','patient','impatient','honest','secretive','confident','shy'];for(const t of traitWords)if(new RegExp(`\\b${t}\\b`,'i').test(joined))traits.push(t);
 const aliasRe=new RegExp(`\\b${escapeReg(name)}\\b[^.!?]{0,45}(?:called|known as|nicknamed)\\s+["'“]?([A-Z][\\w'-]+)`, 'i');const am=joined.match(aliasRe);if(am)aliases.push(am[1]);
 return {id:`char-${slug(name)}`,name,role:'Supporting Character',status:'Active',source:'analyst-auto-discovery',confidence:evidence.length>1?.72:.52,firstAppearance:chapter?.title||chapter?.id||'',firstAppearanceChapterId:chapter?.id||null,aliases,traits,occupation,relationships:[],appearances:chapter?.id?[chapter.id]:[],evidence:evidence.slice(0,3),updatedAt:new Date().toISOString()}}
function relationships(characters,text){const found=[];const names=characters.map(c=>c.name);const patterns=[['mother','parent'],['father','parent'],['mom','parent'],['dad','parent'],['sister','sibling'],['brother','sibling'],['wife','spouse'],['husband','spouse'],['girlfriend','partner'],['boyfriend','partner'],['friend','friend'],['boss','supervisor'],['partner','partner'],['enemy','enemy'],['rival','rival'],['daughter','child'],['son','child']];
 for(const a of names)for(const b of names){if(a===b)continue;for(const [word,type] of patterns){const re1=new RegExp(`\\b${escapeReg(a)}(?:'s)?\\s+${word}\\s*,?\\s*${escapeReg(b)}\\b`,'i');const re2=new RegExp(`\\b${escapeReg(b)}\\b[^.!?]{0,35}\\b${word}\\s+of\\s+${escapeReg(a)}\\b`,'i');if(re1.test(text)||re2.test(text))found.push({from:a,to:b,type,source:'analyst-auto-discovery',confidence:.82})}}
 return unique(found,x=>`${x.from}|${x.to}|${x.type}`)}
function locations(text,chapter){const found=[];const re=new RegExp(`\\b(?:the\\s+)?([A-Z][\\w'-]*(?:\\s+[A-Z][\\w'-]*){0,3}\\s+(?:${PLACE_WORDS}))\\b`,'g');for(const m of String(text||'').matchAll(re))found.push({id:`loc-${slug(m[1])}`,name:norm(m[1]),type:'Location',source:'world-auto-discovery',confidence:.78,firstAppearance:chapter?.title||'',linkedChapters:chapter?.id?[chapter.id]:[]});
 const prep=new RegExp(`\\b(?:at|in|inside|outside|toward|into|from|near)\\s+(?:the\\s+)?([A-Z][\\w'-]*(?:\\s+[A-Z][\\w'-]*){0,2})\\b`,'g');for(const m of String(text||'').matchAll(prep)){const n=norm(m[1]);if(!STOP.has(n)&&n.length>2)found.push({id:`loc-${slug(n)}`,name:n,type:'Location',source:'world-context-discovery',confidence:.48,firstAppearance:chapter?.title||'',linkedChapters:chapter?.id?[chapter.id]:[]})}return unique(found)}
function organizations(text,chapter){const out=[];const re=new RegExp(`\\b([A-Z][\\w'-]*(?:\\s+[A-Z][\\w'-]*){0,4}\\s+(?:${ORG_WORDS}))\\b`,'g');for(const m of String(text||'').matchAll(re))out.push({id:`org-${slug(m[1])}`,name:norm(m[1]),type:'Organization',source:'world-auto-discovery',confidence:.82,firstAppearance:chapter?.title||'',linkedChapters:chapter?.id?[chapter.id]:[]});return unique(out)}
function artifacts(text,chapter){const out=[];const re=/\b(?:the\s+)?([A-Z][\w'-]*(?:\s+[A-Z][\w'-]*){0,3}\s+(?:Sword|Crown|Ring|Necklace|Amulet|Book|Key|Stone|Crystal|Map|Letter|Gun|Blade|Shield|Staff|Orb|Relic|Artifact))\b/g;for(const m of String(text||'').matchAll(re))out.push({id:`artifact-${slug(m[1])}`,name:norm(m[1]),type:'Artifact',source:'world-auto-discovery',confidence:.75,firstAppearance:chapter?.title||'',linkedChapters:chapter?.id?[chapter.id]:[]});return unique(out)}
function timeline(text,chapter){return sentences(text).filter(s=>s.length>25).slice(-8).map((summary,i)=>({id:`event-${chapter?.id||'chapter'}-${hash(summary)}`,title:`${chapter?.title||'Chapter'} event`,summary:summary.slice(0,320),chapterId:chapter?.id||null,chapterTitle:chapter?.title||'',order:i,source:'world-auto-timeline',createdAt:new Date().toISOString()}))}
function ideas(text,chapter){const out=[];const patterns=[/\b(?:planned|promised|swore|vowed|decided|intended|needed|must|would have to)\b/i,/\b(?:secret|mystery|clue|warning|prophecy|threat|goal|plan)\b/i];for(const s of sentences(text)){if(patterns.some(r=>r.test(s)))out.push({id:`idea-${hash(s)}`,text:s.slice(0,300),status:'Future',source:'observer-auto-idea',chapterId:chapter?.id||null,createdAt:new Date().toISOString()})}return unique(out,x=>x.text).slice(-20)}
function slug(s){return key(s).replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,60)||Date.now()}
function hash(s){let h=0;for(const c of String(s))h=(h*31+c.charCodeAt(0))>>>0;return h.toString(36)}
global.HerKnowledge={sentences,properNames,inferCharacter,relationships,locations,organizations,artifacts,timeline,ideas,unique,key};
})(window);
